# Generated by Django 3.0.4 on 2020-05-26 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20200526_1747'),
        ('views', '0004_materializedview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.CronJob', to_field='job_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='views.MaterializedView')),
            ],
        ),
    ]
