# Generated by Django 3.0.4 on 2020-05-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='view',
        ),
    ]
