# Generated by Django 3.0.4 on 2020-05-27 14:37

import channels.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_remove_channel_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_status',
            field=models.CharField(choices=[('ACTIVE', 'Channel is open and active, currently sending events out'), ('INACTIVE', 'Channel has been created, but is not active')], default='INACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='channel',
            name='json_payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=channels.models.default_channels_json_payload),
        ),
        migrations.AddField(
            model_name='channel',
            name='stored_procedure_drop_trigger',
            field=models.FileField(null=True, upload_to='channels'),
        ),
        migrations.AddField(
            model_name='channel',
            name='storedprocedure_create_trigger',
            field=models.FileField(null=True, upload_to='channels'),
        ),
    ]
