# Generated by Django 3.0.4 on 2020-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrefreshes',
            name='status',
            field=models.CharField(choices=[('NEW', 'Event not processed'), ('SENT', 'Event already processed / sent')], default='NEW', max_length=16),
        ),
    ]
