# Generated by Django 3.0.4 on 2020-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_eventrefreshes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrefreshes',
            name='status',
            field=models.CharField(choices=[('NEW', 'New event, not processed / sent'), ('SENT', 'Processed event already sent')], default='NEW', max_length=16),
        ),
    ]
