# Generated by Django 3.0.4 on 2020-06-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0004_materializedview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRefreshes',
        ),
    ]
