version: '3.7'

services:
    web:
        build:
            context: ./app
            dockerfile: production.Dockerfile
        command: gunicorn wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        env_file:
            - ./app/conf/.env.prod
        depends_on:
            - db
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./db/conf/.env.prod
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
