# Generated by Django 3.0.4 on 2020-05-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='user_id',
            new_name='user',
        ),
    ]
