# Generated by Django 3.0.3 on 2020-03-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fav_color',
        ),
    ]
