# Generated by Django 3.0.4 on 2020-05-27 20:35

import channels_app.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20200526_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('storedprocedure_create_trigger', models.FileField(null=True, upload_to='channels')),
                ('stored_procedure_drop_trigger', models.FileField(null=True, upload_to='channels')),
                ('channel_status', models.CharField(choices=[('ACTIVE', 'Channel is open and active, currently sending events out'), ('INACTIVE', 'Channel has been created, but is not active')], default='INACTIVE', max_length=16)),
                ('json_payload', django.contrib.postgres.fields.jsonb.JSONField(default=channels_app.models.default_channels_json_payload)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.CronJob', to_field='job_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
