# Generated by Django 3.0.4 on 2020-06-03 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.CronJob', to_field='job_id'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
