# Generated by Django 3.0.4 on 2020-06-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='stored_procedure_drop_trigger',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='storedprocedure_create_trigger',
        ),
        migrations.AddField(
            model_name='channel',
            name='storedprocedure_file',
            field=models.FileField(null=True, upload_to='channels'),
        ),
    ]
