# Generated by Django 3.0.4 on 2020-05-26 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=datetime.datetime(2020, 5, 26, 16, 25, 50, 993925), max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
    ]
