# Generated by Django 3.0.4 on 2020-06-04 14:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='views.MaterializedView')),
            ],
        ),
        migrations.CreateModel(
            name='EventRefreshes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New event, not processed / sent'), ('SENT', 'Processed event already sent')], default='NEW', max_length=16)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.CronJob')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='views.MaterializedView')),
            ],
        ),
    ]
