# Generated by Django 3.0.4 on 2020-06-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0005_delete_eventrefreshes'),
        ('jobs', '0002_auto_20200526_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRefreshes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New event, not processed / sent'), ('SENT', 'Processed event already sent')], default='NEW', max_length=16)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='views.MaterializedView')),
            ],
        ),
    ]
